import type { NextPage } from 'next'
import { useCallback, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Button from '@mui/material/Button'

const Home: NextPage = () => {
  const [greeting, setGreeting] = useState<string | undefined>()
  const clickCallback = useCallback(() => {
    fetch('/api/hello')
      .then((res) => res.json())
      .then((a) => setGreeting(`Hello ${a.name}`))
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Button variant="contained" onClick={clickCallback}>
          {greeting || 'Click me'}
        </Button>

        <section>
          <Image src="/trees.png" alt="Trees" width={800} height={372} />
        </section>
      </main>
    </div>
  )
}
export default Home
